const fs = require('fs');
const path = 'public/js/avukat-panel.js';
let lines = fs.readFileSync(path, 'utf8').split('\r\n');

// Lines 310-338 (0-indexed: 309-337) are the talepler card block
// Replace with new content
const newLines = [
  `    container.innerHTML = \`<div class="dava-grid">\` +`,
  `      talepler.map(t => \``,
  `        <div class="dava-card" style="\${t.status === 'KABUL' ? 'border-color:var(--accent);' : t.status === 'REDDEDILDI' ? 'border-color:rgba(255,107,107,0.4);opacity:0.7;' : ''}">`,
  `          <div class="dava-card-header">`,
  `            <div style="display:flex;gap:10px;align-items:center;">`,
  `              <div style="width:42px;height:42px;border-radius:50%;background:var(--primary-dark);display:flex;align-items:center;justify-content:center;font-weight:800;font-size:1.1rem;color:#fff;flex-shrink:0;border:2px solid rgba(0,217,163,0.2);">`,
  `                \${t.kullanici?.ad?.charAt(0) || '?'}`,
  `              </div>`,
  `              <div>`,
  `                <div class="dava-card-title">\${t.kullanici?.ad || ''} \${t.kullanici?.soyad || ''}</div>`,
  `                <div class="dava-card-sub">\${t.dava ? t.dava.davaTuru + ' · ' : ''}\${_formatDate()(t.createdAt)}</div>`,
  `              </div>`,
  `            </div>`,
  `            <span class="status-badge status-\${t.status === 'BEKLIYOR' ? 'PENDING' : t.status === 'KABUL' ? 'ACTIVE' : 'REJECTED'}">\${t.status === 'BEKLIYOR' ? '⏳ Bekliyor' : t.status === 'KABUL' ? '✅ Kabul Edildi' : '❌ Reddedildi'}</span>`,
  `          </div>`,
  ``,
  `          \${t.kullanici?.email ? \``,
  `          <div style="margin:0 0 10px 0;padding:10px 14px;background:rgba(0,217,163,0.07);border:1px solid rgba(0,217,163,0.2);border-radius:8px;font-size:0.82rem;">`,
  `            <div style="font-size:0.7rem;color:var(--accent);font-weight:700;text-transform:uppercase;letter-spacing:0.4px;margin-bottom:6px;">✅ İletişim Bilgileri Açıldı</div>`,
  `            <div style="color:var(--text-color);margin-bottom:2px;">📧 \${t.kullanici.email}</div>`,
  `            <div style="color:var(--text-color);">📞 \${t.kullanici.telefon || '—'}</div>`,
  `          </div>`,
  `          \` : ''}`,
  ``,
  `          <div class="dava-card-body" style="padding-top:0">`,
  `            \${t.not ? \``,
  `            <div style="padding:10px 12px;background:rgba(255,255,255,0.04);border-radius:8px;border-left:3px solid rgba(99,102,241,0.6);margin-bottom:12px;">`,
  `              <div style="font-size:0.7rem;color:#818cf8;font-weight:700;text-transform:uppercase;letter-spacing:0.4px;margin-bottom:4px;">📝 Kullanıcı Mesajı</div>`,
  `              <div style="font-size:0.87rem;color:var(--text-color);line-height:1.5;">\${t.not}</div>`,
  `            </div>`,
  `            \` : ''}`,
  ``,
  `            \${t.dava ? \``,
  `            <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px;">`,
  `              <div style="padding:10px 12px;border-radius:8px;background:rgba(0,217,163,0.06);border:1px solid rgba(0,217,163,0.15);text-align:center;">`,
  `                <div style="font-size:0.65rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.4px;margin-bottom:3px;">Tahmini Alacak</div>`,
  `                <div style="font-size:1.05rem;font-weight:800;color:var(--accent);">\${_formatTL()(t.dava.tahminiAlacak)}</div>`,
  `              </div>`,
  `              \${t.dava.skorToplam !== undefined && t.dava.skorToplam !== null ? \``,
  `              <div style="padding:10px 12px;border-radius:8px;background:rgba(255,179,0,0.07);border:1px solid rgba(255,179,0,0.2);text-align:center;">`,
  `                <div style="font-size:0.65rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.4px;margin-bottom:3px;">YZ Dosya Skoru</div>`,
  `                <div style="font-size:1.05rem;font-weight:800;color:#ffb300;">\${t.dava.skorToplam}<span style="font-size:0.65rem;color:var(--text-muted)">/100</span></div>`,
  `              </div>`,
  `              \` : ''}`,
  `            </div>`,
  `            <button onclick="event.stopPropagation(); const d=document.getElementById('talep-detay-\${t.id}'); const ic=document.getElementById('talep-ico-\${t.id}'); if(d.style.display==='none'){d.style.display='block';ic.textContent='▲ Küçült';}else{d.style.display='none';ic.textContent='▼ Dava Analizini Göster';}"`,
  `              style="width:100%;text-align:left;padding:9px 14px;background:rgba(255,255,255,0.05);border:1px solid var(--border);border-radius:8px;cursor:pointer;font-size:0.82rem;color:var(--text-secondary);display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">`,
  `              <span>📊 Tüm Dava Analizini Gör</span>`,
  `              <span id="talep-ico-\${t.id}" style="font-size:0.75rem;color:var(--accent);">▼ Dava Analizini Göster</span>`,
  `            </button>`,
  `            <div id="talep-detay-\${t.id}" style="display:none;">`,
  `              \${renderDetayliDavaRaporu(t.dava.hesaplamaVerisi, t.dava)}`,
  `            </div>`,
  `            \` : \``,
  `            <div style="padding:12px;text-align:center;color:var(--text-muted);font-size:0.85rem;border:1px dashed var(--border);border-radius:8px;">`,
  `              Bu talep bir dava dosyasıyla ilişkili değil.`,
  `            </div>`,
  `            \`}`,
  `          </div>`,
  ``,
  `          <div class="dava-card-actions">`,
  `            \${t.status === 'BEKLIYOR' ? \``,
  `            <button class="btn-primary" style="font-size:0.88rem;padding:11px 16px;width:100%;margin-bottom:8px;background:linear-gradient(135deg,#00d9a3,#00b489);color:#000;font-weight:700;" onclick="iletisimTalebiKabulEt('\${t.id}')">✅ Kabul Et – İletişim Bilgilerini Aç</button>`,
  `            <button class="btn-ghost" style="font-size:0.85rem;padding:10px 16px;width:100%;color:#ff6b6b;border-color:rgba(255,107,107,0.4);" onclick="iletisimTalebiReddet('\${t.id}')">❌ Temsili Reddet</button>`,
  `            \` : \``,
  `              <button class="btn-ghost" style="font-size:0.85rem;padding:10px 16px;width:100%;cursor:not-allowed;" disabled>`,
  `                \${t.status === 'KABUL' ? '✅ Talebi Kabul Ettiniz' : '❌ Talebi Reddettiniz'}`,
  `              </button>`,
  `            \`}`,
  `          </div>`,
  `        </div>`,
  `      \`).join('') + \`</div>\`;`
];

// Patch lines 309-337 (0-indexed)
lines.splice(309, 29, ...newLines);

fs.writeFileSync(path, lines.join('\r\n'), 'utf8');
console.log('✅ Patch yazıldı! Toplam satır:', lines.length);
